# Generated by Django 4.1.3 on 2022-11-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='article_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='artiste',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
