# Generated by Django 4.1.3 on 2022-11-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_rename_song_id_lyric_id_rename_article_id_song_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lyric',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
